#!/usr/bin/perl
use Test::More; # tests=>1;

BEGIN {
use_ok( 'HTTP::Lite' );

}

use strict;
use warnings;

my $http = HTTP::Lite->new;
my $req = $http->request("http://lbg2/perl/miniblog.pl");


$ret=$http->body();
(my $session_id = $ret) =~ s/.*session_id=(.*)&amp;.*/$1/msig;
ok ($session_id=~/^[a-f0-9]+$/, "got session ID: $session_id");

$http->prepare_post({ 
username=>'Admin',
session_id=>$session_id,
password => $ENV{miniblog_pass},
	});
$req = $http->request("http://lbg2/perl/miniblog.pl");

$ret=$http->body();
($session_id=$ret) =~ s/.*session_id=(.*)&amp;.*/$1/msig;

ok ($session_id =~/^[a-f0-9]+$/, "got session ID: $session_id");

my $logged_in = $session_id;

$req = $http->request("http://lbg2/perl/miniblog.pl?action=Articles&amp;session_id=$session_id");

$ret=$http->body();
($session_id=$ret) =~ s/.*session_id=(.*)&amp;.*/$1/msig;

ok ($session_id eq $logged_in, "session ID: matches");

# vim: paste:ai:ts=4:sw=4:sts=4:expandtab:ft=perl
